title: Anwesha Barua
logo: "/images/logo1.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a PhD research scholar at the Centre of Biosystems Science and Engineering (BSSE) in Indian Institute of Science, Bangalore. My current area of research is in biomechanics and liver diseases.  
    <br><br>
  <a href="https://writingsofanunsocialbutterfly.wordpress.com/">Personal blog</a> <br>
  <a href="https://www.linkedin.com/in/anwesha-barua-386972147/">Connect with me on LinkedIn</a><br>
  
  
  
theme: jekyll-theme-minimal
